apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-build 
spec:
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/cooktheryan/signing-blog.git
    - name: revision
      value: main
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
    - name: userHome
      value: /tekton/home
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: build
  - name: buildah
    params:
    - name: IMAGE
      value: quay.io/rcook/signing
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: image/Dockerfile
    - name: CONTEXT
      value: image/
    - name: TAG
      value: $(tasks.git-clone.results.commit)
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: buildah-commit-tag
    workspaces:
    - name: source
      workspace: build
  workspaces:
  - name: build
