apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: image-build
  name: image-build-demo-2
  namespace: signing-test
spec:
  pipelineRef:
    name: image-build
  serviceAccountName: pipeline-signing
  timeout: 1h0m0s
  workspaces:
  - name: build
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
